# Generated by Django 5.1.7 on 2025-04-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="chat_files/")),
                ("file_type", models.CharField(blank=True, max_length=20, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="chat.chatmessage",
                    ),
                ),
            ],
        ),
    ]
